In [9]:
# EJERCICIO 1
import numpy as np

# Vector de tamaño 3
w = np.array([1, 0, 0])

v1 = [-2,4,4]
v2 = [-5,4,0]
v3 = [0,-3,4]
v4 = [8,-4,4]

# Matriz que define la nueva base (cada columna es un vector de la nueva base)
A = np.array([v1, v2, v3]).T  # Necesitamos la traspuesta para que los vectores sean columnas

# Verificar si la base es válida (determinante no nulo)
if np.linalg.det(A) == 0:
    print("La matriz A no es invertible. No define una base.")
else:
    # Calcular la inversa de A
    A_inv = np.linalg.inv(A)

    # Transformar el vector w a la nueva base
    w_in_new_base = A_inv @ w

In [17]:
np.linalg.det(np.array([v2, v3, v4]).T) > 0

True

In [18]:
w_in_new_base

array([ 0.14814815, -0.25925926, -0.14814815])

In [19]:
# Ejercicio 2

In [20]:
import numpy as np

# Definir la matriz A
A = np.array([
    [0, -4, 2, 0],
    [4, 4, 0, -4],
    [-4, 2, 0, 3],
    [8, -8, 2, -6]
])

# Calcular el rango de la matriz
dim = np.linalg.matrix_rank(A)

print("La dimensión del subespacio generado es:", dim)

La dimensión del subespacio generado es: 3


In [21]:
# Ejercicio 5

In [24]:
# (S = T1 o T2)

# Matriz de T1
T1 = np.array([
    [10, 6, 9],
    [1, 5, 2],
    [-4, -1, -7]
])

# Matriz de T2
T2 = np.array([
    [2, 0, -6],
    [-5, 3, 6]
])

# Matriz compuesta T2 o T1
T2_T1 = T2 @ T1

print("Matriz de T1:")
print(T1)

print("\nMatriz de T2:")
print(T2)

print("\nMatriz compuesta T2 o T1:")
print(T2_T1)


Matriz de T1:
[[10  6  9]
 [ 1  5  2]
 [-4 -1 -7]]

Matriz de T2:
[[ 2  0 -6]
 [-5  3  6]]

Matriz compuesta T2 o T1:
[[ 44  18  60]
 [-71 -21 -81]]


In [25]:
import numpy as np

# Definimos los vectores
v = np.array([7, -1, -5])
w = np.array([-1, -7, 6])

# Distancia entre vectores
distancia = np.linalg.norm(v - w)

# Producto punto
producto_punto = np.dot(v, w)

# Normas de los vectores
norma_v = np.linalg.norm(v)
norma_w = np.linalg.norm(w)

# Coseno del ángulo
coseno_angulo = producto_punto / (norma_v * norma_w)

print("Distancia entre vectores:", distancia)
print("Coseno del ángulo entre vectores:", coseno_angulo)


Distancia entre vectores: 14.866068747318506
Coseno del ángulo entre vectores: -0.37354368381881414


In [27]:
v1 = [7,-4,-7]
v2 = [-9,13,10]
v3 = [1,0,1]
v4 = [0,-2,7]


In [32]:
import numpy as np

# Definimos las matrices
R = np.array([
    [-0.5,  0.5,  0.5,  0.5],
    [-0.5,  0.5, -0.5, -0.5],
    [ 0.5,  0.5,  0.5, -0.5],
    [ 0.5,  0.5, -0.5,  0.5]
])

S = np.array([
    [-0.5, -0.5,  0.5,  0.5],
    [-0.5,  0.5, -0.5,  0.5],
    [ 0.5,  0.5, -0.5, -0.5],
    [ 0.5, -0.5,  0.5, -0.5]
])

T = np.array([
    [2, 0, 0, 0],
    [0, 2, 0, 0],
    [0, 0, 2, 0],
    [0, 0, 0, 2]
])

# Verificamos ortogonalidad
R_ortogonal = np.allclose(R.T @ R, np.eye(4))
S_ortogonal = np.allclose(S.T @ S, np.eye(4))
T_ortogonal = np.allclose(T.T @ T, np.eye(4))

print("R es ortogonal:", R_ortogonal)
print("S es ortogonal:", S_ortogonal)
print("T es ortogonal:", T_ortogonal)


R es ortogonal: True
S es ortogonal: False
T es ortogonal: False


In [33]:
# EJERCICIO 9

In [49]:
w = np.array([2, 5, -2])

v1 = [0.6, -0.64, 0.48]
v2 = [0.0, 0.6, 0.8]
v3 = [-0.8,-0.48, 0.36]

# Matriz que define la nueva base (cada columna es un vector de la nueva base)
B = np.array([v1, v2, v3]).T  # Necesitamos la traspuesta para que los vectores sean columnas


In [50]:
# Verificamos la norma de cada columna
normas = np.linalg.norm(B, axis=0)  # Normas columna por columna
es_unitario = np.allclose(normas, 1)  # Todas las normas son ~1

# Verificamos la ortogonalidad
producto_interno = B.T @ B  # Producto interno de las columnas
identidad = np.eye(3)  # Matriz identidad de tamaño 3
es_ortonormal = np.allclose(producto_interno, identidad)

# Resultados
print("Normas de las columnas:", normas)
print("¿Es ortonormal?:", es_ortonormal)

Normas de las columnas: [1. 1. 1.]
¿Es ortonormal?: True


In [51]:
# Vector en la base canónica
w = np.array([2, 5, -2])

# Coordenadas en la nueva base
w_prime = B.T @ w  # Usamos la transpuesta de B para calcular las coordenadas
print("Coordenadas de w en la nueva base:", w_prime)

Coordenadas de w en la nueva base: [-2.96  1.4  -4.72]


# Entrega 3

In [53]:
import numpy as np

# Datos
x = np.array([-11, -7, -3, 3, 9, 12])
y = np.array([-49, -30, -8, 27, 43, 61])

# Ajuste de una función cuadrática (grado 2)
coefficients = np.polyfit(x, y, 2)  # Devuelve [a2, a1, a0]

# Separar los coeficientes
a2, a1, a0 = coefficients

# Imprimir resultados
print(f"a0 = {a0}")
print(f"a1 = {a1}")
print(f"a2 = {a2}")

a0 = 8.189529917341892
a1 = 4.807541219736571
a2 = -0.04736029821612848


In [58]:
import numpy as np

# Vectores en R4
u = np.array([2, -1, 3, -3])  # Reemplaza con los valores del vector u
v = np.array([4,-4,4,1])  # Reemplaza con los valores del vector v

# Producto escalar
dot_product = np.dot(u, v)

# Normas de los vectores
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)

# Cálculo del ángulo en radianes
cos_theta = dot_product / (norm_u * norm_v)

# Asegurar que cos_theta esté en el rango [-1, 1] por posibles errores numéricos
cos_theta = np.clip(cos_theta, -1, 1)

# Ángulo en radianes
theta = np.arccos(cos_theta)

# Convertir a grados si es necesario
theta_degrees = np.degrees(theta)

print(f"Ángulo en radianes: {theta}")
print(f"Ángulo en grados: {theta_degrees}")


Ángulo en radianes: 0.8949686928962144
Ángulo en grados: 51.27792889929299


In [60]:
import numpy as np

# Definir los vectores del subespacio
u = np.array([2,-1,3,-3])  # Reemplaza con los valores de u
v = np.array([4, -4, 4, 1])  # Reemplaza con los valores de v
w = np.array([5,-1 , -2, -1])  # Reemplaza con los valores de w

# Definir el punto P
P = np.array([-2, 0, -4, -2])  # Reemplaza con los valores de P

# Crear la matriz de vectores base del subespacio
A = np.column_stack((u, v, w))  # Matriz cuyas columnas son u, v y w

# Resolver el sistema de proyección
# Resuelve el sistema A.T @ A @ c = A.T @ P para obtener los coeficientes c
c = np.linalg.lstsq(A, P, rcond=None)[0]  # Coeficientes de la combinación lineal

# Reconstruir el punto proyectado R
R = A @ c  # Punto en el subespacio más cercano a P

# Extraer el valor de r_1
r_1 = R[0]

print(f"El valor de r_1 es: {r_1}")


El valor de r_1 es: -0.9816060016671306


In [63]:
import numpy as np

# Vectores candidatos
vectors = [
    np.array([1, -2, 1, 1]),  # Opción a
    np.array([1, 1, 2, -1]),  # Opción b
    np.array([1, 0, 0, 1]),   # Opción c
    np.array([0, -2, 1, 0])   # Opción d
]

# Base de S
# Restricciones: x2 + 2x3 = 0 -> x2 = -2x3, y x1 = x4 -> x1 = t
basis_S = [
    np.array([1, 0, 0, 1]),   # De x1 = x4 y x2 = x3 = 0
    np.array([0, -2, 1, 0])   # De x2 = -2x3
]

# Verificar ortogonalidad
for i, v in enumerate(vectors):
    is_orthogonal = all(np.dot(v, b) == 0 for b in basis_S)
    print(f"El vector {chr(97 + i)} {'pertenece' if is_orthogonal else 'NO pertenece'} a S^⊥.")


El vector a NO pertenece a S^⊥.
El vector b pertenece a S^⊥.
El vector c NO pertenece a S^⊥.
El vector d NO pertenece a S^⊥.


In [64]:
import numpy as np

# Definir el punto A
A = np.array([2, 5, 5, 2])

# Base del subespacio S
# Restricciones: x2 + 2x3 = 0 y x1 - x4 = 0
# Representación paramétrica:
# x = t1 * [1, 0, 0, 1] + t2 * [0, -2, 1, 0]
basis = np.array([
    [1, 0, 0, 1],  # Primer vector base
    [0, -2, 1, 0]  # Segundo vector base
])

# Proyección ortogonal de A sobre el subespacio generado por basis
# P = A @ basis @ (basis^T @ basis)^-1 @ basis^T
B = basis.T
projection = B @ np.linalg.inv(B.T @ B) @ B.T @ A

# Extraer x_3
x_3 = projection[2]
print(f"x_3 = {x_3}")


x_3 = -1.0


In [65]:
import numpy as np

# Definir el punto A
A = np.array([2, 5, 5, 2])

# Base del subespacio S
# x1 = x4, x2 = -2x3
basis = np.array([
    [1, 0, 0, 1],  # Primer vector base (x1 = x4)
    [0, -2, 1, 0]  # Segundo vector base (x2 = -2x3)
])

# Proyección ortogonal de A sobre el subespacio generado por basis
B = basis.T
projection = B @ np.linalg.inv(B.T @ B) @ B.T @ A

# Calcular la distancia entre A y la proyección (punto más cercano)
distance_vector = A - projection
distance = np.linalg.norm(distance_vector)

# La distancia es la raíz cuadrada de k, por lo tanto, k es el cuadrado de la distancia
k = distance**2
print(f"k = {k}")


k = 45.00000000000001


In [66]:
import numpy as np

# Example matrix A and vector v
A = np.array([[1, 3, 0], 
              [0, 5, -3],
              [0, -9, 11]])
v = np.array([3, 1, 1])

# Check if v is an eigenvector of A
Av = np.dot(A, v)  # A * v
lambda_v = Av / v  # Compute the ratio

# Check if the ratio is consistent
if np.allclose(lambda_v, lambda_v[0]):
    print(f"v is an eigenvector of A with eigenvalue {lambda_v[0]}")
else:
    print("v is not an eigenvector of A")

v is an eigenvector of A with eigenvalue 2.0


In [67]:
A = np.array([[-90, 90, -126], 
              [90, -171, -36],
              [-126, -36, -63]])
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Check if the number of linearly independent eigenvectors equals the size of the matrix
if np.linalg.matrix_rank(eigenvectors) == A.shape[0]:
    print("The matrix is diagonalizable.")
else:
    print("The matrix is not diagonalizable.")

The matrix is diagonalizable.


In [70]:
B = np.array([[-0.5774, 0, 0.8165], 
              [-0.5774, -0.7071, -0.4082],
              [-0.5774, -0.7071, -0.4082]])
# Step 2: Check if columns of B are linearly independent
if np.linalg.matrix_rank(B) == B.shape[1]:
    print("The columns of B are linearly independent.")

    # Step 3: Check if B is a matrix of eigenvectors of A
    # A * B should be equal to B * D where D is a diagonal matrix of eigenvalues
    D = np.diag(eigenvalues)
    if np.allclose(np.dot(A, B), np.dot(B, D)):
        print("B is a basis of eigenvectors of A.")
    else:
        print("B is not a basis of eigenvectors of A.")
else:
    print("The columns of B are not linearly independent.")

The columns of B are not linearly independent.


In [74]:
# EJ 12

A = np.array([[4, 2, 2], 
              [2, 4, 2],
              [2, 2, 4]])
# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Check if the number of linearly independent eigenvectors equals the size of the matrix
if np.linalg.matrix_rank(eigenvectors) == A.shape[0]:
    print("The matrix is diagonalizable.")
else:
    print("The matrix is not diagonalizable.")

The matrix is diagonalizable.


In [87]:
B = np.array([[8, 0, 0], 
              [0, 2, 0],
              [0, 0, 2]])

eigenvalues_b, eigenvectors_b = np.linalg.eig(B)


In [88]:
eigenvalues

array([2., 8., 2.])

In [89]:
eigenvalues_b

array([8., 2., 2.])

In [90]:
import numpy as np

# Definir la matriz diagonal D
D = np.array([[-4, 0, 0],
              [0, 3, 0],
              [0, 0, -1]])

# Matriz C: por ahora asumimos que C es una matriz invertible aleatoria, ya que no se nos da explícita
C = np.array([[1, 0, 0], 
              [0, 1, 0], 
              [0, 0, 1]])  # Aquí podemos cambiar C por cualquier otra matriz invertible

# Calculamos la matriz A usando A = C^-1 * D * C
A = np.linalg.inv(C) @ D @ C

# 1. Verificar el rango de A
rango_A = np.linalg.matrix_rank(A)
print(f"Rango de A: {rango_A}")  # A debería tener rango 3 si es invertible

# 2. Verificar si A * C = C * D (esto no es cierto, como discutimos)
A_C = A @ C
C_D = C @ D
print(f"A * C == C * D? {np.allclose(A_C, C_D)}")

# 3. Verificar la dimensión del autoespacio para el autovalor 3
# Los autovalores de D son los mismos que los de A
autovalores, _ = np.linalg.eig(D)
print(f"Autovalores de D (y A): {autovalores}")
# Verificamos que el autovalor 3 tiene multiplicidad algebraica 1, por lo que su autoespacio tiene dimensión 1
dimension_autoespacio_3 = np.sum(np.isclose(autovalores, 3))
print(f"Dimensión del autoespacio asociado al autovalor 3: {dimension_autoespacio_3}")

# 4. Verificar si el determinante de A es distinto de cero
determinante_A = np.linalg.det(A)
print(f"Determinante de A: {determinante_A}")  # Debería ser distinto de cero

# 5. Verificar si tenemos información suficiente sobre los autovalores de A
# Como A es similar a D, sus autovalores son los mismos
informacion_suficiente = len(autovalores) > 0
print(f"¿Tenemos suficiente información para saber los autovalores de A? {informacion_suficiente}")

# 6. Verificar si λ = -4 es autovalor de A y si (1, 0, 0) es un autovector correspondiente
# Sabemos que los autovalores de A son los mismos que los de D, y -4 es uno de ellos.
# También sabemos que (1, 0, 0) es un autovector correspondiente al autovalor -4 para D.

autovalor_minus_4 = np.isclose(autovalores, -4)
print(f"¿λ = -4 es autovalor de A? {np.any(autovalor_minus_4)}")
print(f"¿(1,0,0) es un autovector correspondiente a λ = -4? {'Sí, es un autovector' if np.any(autovalor_minus_4) else 'No'}")


Rango de A: 3
A * C == C * D? True
Autovalores de D (y A): [-4.  3. -1.]
Dimensión del autoespacio asociado al autovalor 3: 1
Determinante de A: 12.0
¿Tenemos suficiente información para saber los autovalores de A? True
¿λ = -4 es autovalor de A? True
¿(1,0,0) es un autovector correspondiente a λ = -4? Sí, es un autovector
